#macro VIEW_TO_WINDOW_SCALE 4

#macro BASE_WINDOW_WIDTH BASE_VIEW_WIDTH * VIEW_TO_WINDOW_SCALE
#macro BASE_WINDOW_HEIGHT BASE_VIEW_HEIGHT * VIEW_TO_WINDOW_SCALE

window_set_size(BASE_WINDOW_WIDTH,BASE_WINDOW_HEIGHT);
surface_resize(application_surface, BASE_WINDOW_WIDTH,BASE_WINDOW_HEIGHT);

